package ru.bigbuzzy.monitor.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import javax.sql.DataSource;

/**
 * User: volodko
 * Date: 11.01.12
 * Time: 10:56
 */
@Service
public class JdbcSchemaCreator {
    private static final Logger logger = LoggerFactory.getLogger(JdbcSchemaCreator.class);

    private JdbcTemplate jdbcTemplate;

    @Autowired
    public void setDataSource(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
        doExecute();
    }

    public void doExecute() {
        logger.debug("Method doExecute has started...");
        this.jdbcTemplate.execute(
                "create table resource(" +
                        " id bigint generated by default as identity (start with 1) primary key," +
                        " login varchar(32)," +
                        " password varchar(32)," +
                        " path varchar(255)," +
                        " host varchar(64)," +
                        " port int," +
                        " protocol varchar(32)," +
                        " response_code int," +
                        " response_size bigint," +
                        " connection_timeout bigint," +
                        " socket_timeout bigint," +
                        " email varchar(255)" +
                        ")"
        );
        logger.debug("Table resource has created...");

        this.jdbcTemplate.execute(
                "create table resource_status(" +
                        " id bigint generated by default as identity (start with 1) primary key," +
                        " create_time timestamp not null," +
                        " response_code int," +
                        " response_size bigint," +
                        " response_timeout bigint," +
                        " is_status_exception boolean," +
                        " status_message varchar(255)," +
                        " fk_resource bigint not null," +
                        " foreign key (fk_resource) references resource(id)" +
                        ")"
        );
        logger.debug("Table resource_status has created...");
    }
}
